apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: automl-worker-scaler
  namespace: staging
spec:
  scaleTargetRef:
    name: automl-worker
  pollingInterval: 30 # Check queue every 30 seconds
  cooldownPeriod: 300 # Wait 5 minutes before scaling down
  # idleReplicaCount: 1  # Scale to 1 when no messages
  minReplicaCount: 1 # Minimum pods when scaling
  maxReplicaCount: 50 # Maximum pods
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        host: amqp://guest:guest@rabbitmq-service.staging.svc.cluster.local:5672/
        queueName: automl # Your actual queue name
        queueLength: "1" # Target queue length per pod
        # Optional: Add these for better control
        # excludeUnacknowledged: 'false'  # Include unacked messages
        # vhostName: '/'  # Virtual host name
