resources:
  - staging/app/common
  - staging/app/rabbitmq
  - staging/app/redis
  - staging/app/mongodb
  - staging/app/api
  - staging/app/clustering-worker
  - staging/app/streamlit
  - staging/ingress
  - keda
