apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  namespace: prod
  labels:
    app: flower
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,RespectIgnoreDifferences=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: patrickmeyer/caas-clustering-worker # Will be replaced by kustomize
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "workers.tasks", "flower", "--port=5555"]
        envFrom:
        - configMapRef:
            name: caas-config
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672/"
        - name: FLOWER_UNAUTHENTICATED_API
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
    
---
apiVersion: v1
kind: Service
metadata:
  name: flower-service
  namespace: prod
spec:
  selector:
    app: flower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: flower-nodeport
  namespace: prod
spec:
  selector:
    app: flower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
      nodePort: 30055
  type: NodePort