apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: staging
data:
  01-init-mongo.js: |
    // init-mongo.js
    db = db.getSiblingDB('caas'); // creates or switches to 'caas'
    db.createCollection('data'); // creates a collection
    db.createCollection('results'); // creates a collection