apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustering-worker
  namespace: staging
  labels:
    app: clustering-worker
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,RespectIgnoreDifferences=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  replicas: 1 # KEDA will manage replicas
  selector:
    matchLabels:
      app: clustering-worker
  template:
    metadata:
      labels:
        app: clustering-worker
    spec:
      containers:
        - name: clustering-worker
          image: patrickmeyer/caas-clustering-worker # Will be replaced by kustomize
          imagePullPolicy: IfNotPresent
          command:
            [
              "celery",
              "-A",
              "workers.clustering.worker_tasks",
              "worker",
              "--pool=solo",
              "--loglevel=info",
              "--concurrency=1",
              "--max-tasks-per-child=1",
              "--without-gossip",
              "--without-mingle",
            ]
          envFrom:
            - configMapRef:
                name: caas-config
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq-service:5672/"
            - name: QUEUE_NAME
              value: "clustering_jobs"
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          # Faster startup for scale-from-zero
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"] # Shorter grace period
      terminationGracePeriodSeconds: 30 # Shorter grace period
