apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: clustering-worker-scaler
  namespace: staging
spec:
  scaleTargetRef:
    name: clustering-worker
  pollingInterval: 10 # Check queue every 10 seconds
  cooldownPeriod: 180 # Wait 3 minutes before scaling down
  # idleReplicaCount: 0  # Scale to 0 when no messages
  minReplicaCount: 1 # Minimum pods when scaling
  maxReplicaCount: 10 # Maximum pods
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        host: amqp://guest:guest@rabbitmq-service.staging.svc.cluster.local:5672/
        queueName: celery # Your actual queue name
        queueLength: "1" # Target queue length per pod
        # Optional: Add these for better control
        # excludeUnacknowledged: 'false'  # Include unacked messages
        # vhostName: '/'  # Virtual host name
