apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustering-worker
  namespace: staging
  labels:
    app: clustering-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustering-worker
  template:
    metadata:
      labels:
        app: clustering-worker
    spec:
      containers:
      - name: clustering-worker
        image: patrickmeyer/caas-clustering-worker # Will be replaced by kustomize
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: caas-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo "Waiting for RabbitMQ..."; sleep 2; done;']
