apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: prod
  labels:
    app: mongodb
spec:
  clusterIP: None  # This makes it headless (required for StatefulSet)
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: prod
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongodb
