apiVersion: v1
kind: ConfigMap
metadata:
  name: caas-config
  namespace: staging
data:
  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  RABBITMQ_DEFAULT_VHOST: /
  RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbit loopback_users []'
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # MongoDB Configuration
  MONGODB_DB: "caas"
  MONGODB_HOST: "mongodb-service"
  MONGODB_PORT: "27017"
  
  # FastAPI Configuration
  FASTAPI_HOST: "fastapi-service"
  FASTAPI_PORT: "8000"
  FASTAPI_PROTOCOL: "http"

  # Flower Configuration
  FLOWER_URL: "http://flower-service:5555"
