apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: prod
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: minio
  selector:
    app: minio
