apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: staging
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: patrickmeyer/caas-streamlit # Will be replaced by kustomize
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: caas-config
          environment:
            - name: STREAMLIT_SERVER_MAX_UPLOAD_SIZE
              value: 2048
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: staging
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-nodeport
  namespace: staging
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30501
  type: NodePort
